version: "2"

services:

  proxy_demo:
    image: nginx
    ports:
        - "8045:80"
    volumes:
      -  ./default.conf:/etc/nginx/conf.d/default.conf
networks:
    default:
      external:
        name: ols_dev